//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaldeiraoFurado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acomodacoes
    {
        public short acomodacao_ID { get; set; }
        public string tipo_de_acomodacao { get; set; }
        public string andar { get; set; }
        public string num_quarto { get; set; }
        public string room_service { get; set; }
    }
}
