//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaldeiraoFurado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frigobar_estadia
    {
        public short frigobar_ID { get; set; }
        public string estadia_ID { get; set; }
        public string nome_hospede { get; set; }
        public string cod_item { get; set; }
        public Nullable<System.DateTime> data_consumida { get; set; }
    }
}
