//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaldeiraoFurado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionarios
    {
        public short funcionarios_ID { get; set; }
        public string nome { get; set; }
        public string endereco { get; set; }
        public System.DateTime nascimento { get; set; }
        public string telefone { get; set; }
    }
}
