//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaldeiraoFurado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itens_consumo
    {
        public long cod_item { get; set; }
        public string descricao { get; set; }
        public Nullable<double> preco_venda { get; set; }
    }
}
