//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaldeiraoFurado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservas
    {
        public short reserva_ID { get; set; }
        public string funcionario_ID { get; set; }
        public Nullable<System.DateTime> check_in { get; set; }
        public Nullable<System.DateTime> check_out { get; set; }
        public string hospede_principal { get; set; }
        public string tipo_de_acomodacao { get; set; }
        public string acompanhantes { get; set; }
        public Nullable<double> valor_da_diaria { get; set; }
        public Nullable<double> taxa_de_multa { get; set; }
        public string desconto { get; set; }
        public string hospede_ID { get; set; }
    }
}
